#!/usr/bin/env php
<?php
set_time_limit(0);

require 'vendor/autoload.php';

use Monolog\Logger;
use Monolog\Handler\RotatingFileHandler;

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;

use Posibrain\TchatBot;

$console = new Application();

// Add command
$console
	->register('submit')
	->setDefinition(array(
		new InputArgument('message', InputArgument::REQUIRED, 'Message of the requestor'),
		new InputArgument('name', InputArgument::OPTIONAL, 'Name of the requestor'),
	))
	->setDescription('Discuss with a posibrained bot')
	->setCode(function (InputInterface $input, OutputInterface $output) {
		$userName = $input->getArgument('name');
		if (empty($userName)) {
			$userName = 'You';
		}
		$userMessage = $input->getArgument('message');
		
		$logger = new Logger('TchatBotConsole');
		if (! is_dir(__DIR__ . '/../logs/')) {
			mkdir(__DIR__ . '/../logs/');
			chmod(__DIR__ . '/../logs/', '755');
		}
		$loggerHandler = new RotatingFileHandler(__DIR__ . '/../logs/console.log', 2, Logger::DEBUG);
		$logger->pushHandler($loggerHandler);
		$bot = new TchatBot('', '', array(
		    'loggerHandler' => $loggerHandler
		));
		$answer = $bot->generateAnswer($userMessage, $userName, time());

		$output->writeln(sprintf('%s: %s', @$answer[1], @$answer[0]));
	})
;

// Run
$console->run();
